### ISSUE TITLE
feature request: Emacs/ixml mode

### ISSUE THREAD

**Issue by sydb** [nineml/coffeepot#53]
I would love to have an Emacs major mode for editing an Invisible XML grammar, to include things like
- syntax coloring;
- completion of non-terminals;
- some easy keystroke that gives me a syntax cheat sheet;
- a key binding for “run CoffeePot with this grammar as the --grammar:, prompting me for the --input: (using the last file as the default)”, --output: to /tmp/ with same name (but “.xml” extension) or some such.

This major mode should be called “ixml-mode”, of course, but I think it would be more fun to call it “CoffeeCake”.

Bonus: I have been including as a comment in my .ixml files a RELAX NG compact syntax schema to which I expect the output to be valid. Would be lovely if that were color syntaxed, too.

Yes, you are allowed to think “you know Emacs Lisp, write it yourself, Syd”, but a) color sytnaxing is a bit beyond my meager skills, and b) I cannot imagine having time until late Fall at the earliest. Heck, I can barely find time to work on my Invisible XML grammar. (Although I would be more likely to work on it if I had a nice major mode. :-)

**Comment by ndw** [comment]
I tinkered with this a while back unsuccessfully, but I hope to return to it one day.

**Comment by ndw** [comment]
Done. https://github.com/nineml/tree-sitter-ixml/

Emacs 29 required, I'm afraid, Syd, but totally worth it.

Also perhaps of interest: https://so.nwalsh.com/2023/08/22-tree-sitter-ixml
