### ISSUE TITLE
How do you reference regex pragma in the rule it annotates?

### ISSUE THREAD

**Issue by rosswmerrifield** [nineml/coffeepot#68]
The documentation doesn't specify this. For example, with the following 'rules.ixml' file:

```
{[+pragma nineml "https://nineml.org/ns/pragma/"]} 

document: myregex .
{[nineml regex ".*"]}
myregex: . 
```

ran with the following command:

`coffeepot -pp -g:rules.ixml "hello"`

I get the error:

```
<fail xmlns:ixml="http://invisiblexml.org/NS" ixml:state="failed">
   <line>1</line>
   <column>2</column>
   <pos>1</pos>
   <unexpected>h</unexpected>
</fail>
```

This is unexpected because the regex should match anything (and changing my regex to a literal `"hello"` results in the same error). I'm guessing the error is because I'm not doing something correctly here. Maybe a brief example in the documentation would be useful? I am using CoffeePot version 1.99.12.

**Comment by ndw** [comment]
I believe I've fixed the regex pragma and improved [the documentation](https://coffeepot.nineml.org/ch09.html#pragma-regex). Your example now works. Thank you for the bug report!
